### ISSUE TITLE
验证自己训练的model的时候出错

### ISSUE THREAD

**Issue by gydlcc** [zfxxfeng/cnn_lstm_ctc_ocr_for_ICPR#3]
我用了你的预训练模型训练了大概30万次
然后 我输入python validate.py出现下面错误
![2018-06-08 11-17-13](https://user-images.githubusercontent.com/26570842/41137508-feae0568-6b0d-11e8-8dfc-0c2002ccbb43.png)
何解？

**Comment by zfxxfeng** [comment]
个人建议：1在不训练自己数据的情况下，运行validate.py,若有输出，则认为是数据处理不好，使模型失去预测能力。2建议使用绝对路径。3从个人情感出发，我希望在使用代码之前，star或者fork，谢谢合作。

**Comment by gydlcc** [comment]
OK，给你star了，我再问一下就是你百度云里的数据 是全部的icpr 的数据吗？怎么感觉tfrecod的内存很小。
![default](https://user-images.githubusercontent.com/26570842/41498839-9d581b80-71a9-11e8-89d0-3051bd2c0d03.PNG)

**Comment by zfxxfeng** [comment]
不是全部，个人建议自己跑下代码熟悉一下数据处理过程

**Comment by gydlcc** [comment]
好的 多谢

**Comment by gydlcc** [comment]
唉，那个那个icpr的数据集我好像没有下载权限，你能不能分享到我的百度网盘 百度帐号gydlcc

**Comment by zfxxfeng** [comment]
链接: https://pan.baidu.com/s/1lvSVyXQv6y2YXxG0HJXBhw 密码: mck3

**Comment by gydlcc** [comment]
OK，非常感谢

**Comment by gydlcc** [comment]
额，那个你的getTxt.py是不是有问题啊，为什么执行之后什么结果都没有 也不报错

**Comment by gydlcc** [comment]
@zfxxfeng  我按照你的readme 里的步骤 先用getTxt.py  获得txt 然后再用target_cut.py 抠图 但是抠出来的图好像不对 如下图，这是为什么呀？
![2018-06-22 11-00-52](https://user-images.githubusercontent.com/26570842/41755940-4c470a6e-760c-11e8-90e8-cb558818b8fd.png)

**Comment by gydlcc** [comment]
@zfxxfeng 里面的word_dict.py 是什么作用？ 意思是把识别当作分类问题了吗？
