### ISSUE TITLE
raw data set

### ISSUE THREAD

**Issue by zfxxfeng** [zfxxfeng/cnn_lstm_ctc_ocr_for_ICPR#7]
链接: https://pan.baidu.com/s/1lvSVyXQv6y2YXxG0HJXBhw 密码: mck3

**Comment by zfxxfeng** [comment]
链接: https://pan.baidu.com/s/1rxSkww40sppI4oVEaKHQAA 提取码: gx19 
This is the link of processed data.The label of images in a txt file.

**Comment by cloudfool** [comment]
Hi,
你提供的第一个链接里的有ICPR_task3_test_20180514。请问有没有ICPR_task1_test_20180514?
谢谢

**Comment by zfxxfeng** [comment]
ICPR_task3_test_20180514 and ICPR_task1_test_20180514 have the same content

**Comment by cloudfool** [comment]
哦哦。
