### ISSUE TITLE
How many steps do you run when training denseNet on IPCR dataset?

### ISSUE THREAD

**Issue by tabsun** [zfxxfeng/cnn_lstm_ctc_ocr_for_ICPR#8]
Much thanks to your work!

I haved trained the network for 70k steps and the effect is still bad. As your uploaded model's step is 1405532,  I really need a long way to go, right?

Another question is, model.ckpt-1405532 will predict 5530 characters, but the word_dict.py contains 16389 characters. Where's the corresponding word_dict for the demo model?

**Comment by zfxxfeng** [comment]
I upload the model （1405532） that is resnet.Maybe DenseNet need to be modified，because it is hard to converge.You can check the word_dict.py in the src file.

**Comment by tabsun** [comment]
I can see only a "out_charset" in word_dict and its length is 16k almost. So I wonder if the model.ckpt-1405532 is trained on 16k characters or 5k characters?

**Comment by zfxxfeng** [comment]
out_charset is 5k characters.1405532 is trained on 5K

**Comment by tabsun** [comment]
Much Thanks！
